---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: linux
    image: diodonfrost/${image:-ansible-centos:8}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    env:
      packer_version: "${packer_version:-latest}"
provisioner:
  name: ansible
verifier:
  name: ansible
